s = input("Enter your name : ")
print(f"Name capitalize : {s.capitalize()}")
print("Your name have")
print(f"Find a in name = {s.count("a")}")
print(f"Find e in name = {s.count("e")}")
print(f"Find i in name = {s.count("i")}")
print(f"Find o in name = {s.count("o")}")
print(f"Find u in name = {s.count("u")}")
print(f"Find \"chai\" in name = {s.find("chai")}")
print(f"Index \"som\" in name = {s.index("som")}")
print(f"Replace chai with sak : {s.replace("chai","sak")}")